### PR TITLE
tilemap example added

### PR DESCRIPTION
**Pull request by zcking**
This example, as first mentioned in a Pixel issue [here](https://github.com/faiface/pixel/issues/18#issuecomment-460021772), demonstrates the use of tilemaps in Pixel, using the Tiled TMX format and a simple level loaded from a file (JSON).

### CODE REVIEW

**Comment by faiface** [comment]
Thanks! But I'm a little confused right now about the two files you have: one `.tmx` and one `.json`. Doesn't the `.tmx` file already contain a description of a level/scene?

**Comment by zcking** [comment]
Yes @faiface thanks for pointing that out. I misunderstood some of the data in the TMX file--thinking it was purely defining tile sizing and dimension information in relation to its source image(s). I see that now, having opened the TMX file in Tiled... Allow me to research a bit further and revisit this example.

**Comment by faiface** [comment]
Awesome :)

**Comment by zcking** [comment]
Took a bit of finaggling to get the math worked out, but code has been updated to read all its "level" data now from the TMX file. I also added the same camera logic from the wiki to allow the user to pan around and view the whole level. All previous unnecessary JSON level serialization removed.

**Comment by faiface** [comment]
Okay, this looks good now. Thanks a lot :)

**Comment by faiface** [comment]
Oh, I just noticed one thing.

You have a pretty bad performance because you're drawing everything directly to the window. A draw to the window results in an OpenGL call, which is not very fast.

Instead, you should be using a Batch (learn about it here, if you haven't already: https://github.com/faiface/pixel/wiki/Drawing-efficiently-with-Batch).

So if you'd be so kind, I'd really appreciate it if you updated the example with batch. Thanks.

**Pull request merged**
