### PR TITLE
Line collision

### PR DESCRIPTION
**Pull request by bcvery1**
I've  been using this to visualise the issues with floating point inaccuracy (fix is imminent on that issue btw)

This is a nice simple example with visual feedback to what is going on

### CODE REVIEW

**Comment by faiface** [comment]
Hey, thanks for this! Could you please add a screenshot? I'll merge then.

**Comment by bcvery1** [comment]
Thanks, added!

**Comment by bcvery1** [comment]
Ping @faiface

**Comment by faiface** [comment]
Sorry, I forgot about this :D. Thanks! Merging.

**Pull request merged**
